name: example
description: Sample project for Very Good Performance
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test:
  very_good_analysis: ^2.4.0
  very_good_performance:
    path: ../

flutter:
  uses-material-design: true
