name: very_good_performance
description: Utility on top of the Flutter Driver API that facilitates measuring the performance of your app in an automated way
version: 0.0.4
homepage: https://github.com/VeryGoodOpenSource/very_good_performance

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  ansicolor: ^2.0.1
  barbecue: ^0.4.0
  checked_yaml: ^2.0.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_annotation: ^4.7.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
