name: very_good_performance
description: Utility on top of the Flutter Driver API that facilitates measuring the performance of your app in an automated way
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  ansicolor: ^2.0.1
  barbecue: ^0.4.0
  checked_yaml: ^2.0.1
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^4.1.2
  very_good_analysis: ^2.0.0

flutter:
